# Generated by Django 4.2.9 on 2024-05-20 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(default=None, upload_to='fotos/fotos_productos/')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(default='fotos/default.png', upload_to='fotos_productos/')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ventaSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(help_text='Descripción del producto')),
                ('foto', models.ImageField(default='fotos_paquetes/default.png', upload_to='fotos_paquetes/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombreCompleto', models.CharField(max_length=254)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('rol', models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('EMPLE', 'Empleado'), ('USUAR', 'Usuario')], default='USUAR', max_length=5, null=True)),
                ('foto', models.ImageField(default='fotos/default.png', upload_to='fotos/')),
                ('token', models.CharField(blank=True, max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.IntegerField(blank=True, null=True)),
                ('materiaPrima', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.materiaprima')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('cantidad_movida', models.IntegerField()),
                ('estado', models.CharField(blank=True, choices=[('1', 'Entrada'), ('2', 'Salida'), ('3', 'Bodega')], default='1', max_length=5, null=True)),
                ('almacenes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.almacen')),
                ('materiaPrima', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.materiaprima')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.productoterminado')),
            ],
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='proveedores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.proveedor'),
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.ImageField(default='fotos/default.png', upload_to='fotos/fotos_productos/')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pedidos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.pedido')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.productoterminado')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Creado'), (2, 'Enviado'), (3, 'Cancelado')], default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nivel_Minimo', models.IntegerField()),
                ('fecha_vencimiento', models.IntegerField()),
                ('materiaPrima', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.materiaprima')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.productoterminado')),
            ],
        ),
    ]
