# Generated by Django 4.2.9 on 2024-06-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoterminado',
            name='cantidad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='precio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
