# Generated by Django 4.2.9 on 2024-07-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_productoterminado_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('SECRE', 'Secretaria'), ('VENDE', 'Vendedor'), ('USUAR', 'Usuario')], default='USUAR', max_length=5, null=True),
        ),
    ]
