# Generated by Django 5.0.7 on 2024-08-03 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='API.productoterminado'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
