# Generated by Django 4.2.9 on 2024-08-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrador'), ('GEREN', 'Gerente'), ('USUAR', 'Usuario')], default='USUAR', max_length=5, null=True),
        ),
    ]
