# Generated by Django 5.0.7 on 2024-08-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_pedido_cantidad_pedido_precio_total_pedido_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
