# Generated by Django 4.2.9 on 2024-08-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_usuario_rol'),
        ('API', '0005_pedido_precio_unitario'),
    ]

    operations = [
    ]
