# Generated by Django 4.2.9 on 2024-09-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_merge_20240827_0855'),
        ('API', '0006_merge_20240829_1447'),
    ]

    operations = [
    ]
