# Generated by Django 4.2.9 on 2024-10-08 00:06

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_merge_20240901_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiaprima',
            name='proveedores',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='almacenes',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='materiaPrima',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='materiaPrima',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='productos',
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='clientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.cliente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=254, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.DeleteModel(
            name='AlertaStock',
        ),
        migrations.DeleteModel(
            name='MateriaPrima',
        ),
        migrations.DeleteModel(
            name='MovimientoStock',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
