# Generated by Django 4.2.9 on 2024-10-08 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_pedido_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='El motivo debe contener solo letras y espacios', regex='^[A-Za-z\\s]+$')]),
        ),
    ]
