# Generated by Django 4.2.9 on 2024-10-08 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_devolucion_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoterminado',
            name='cantidad',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='lote',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='El lote debe contener solo letras, números y guiones.', regex='^[A-Za-z0-9\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre debe contener solo letras y espacios.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
