# Generated by Django 4.2.9 on 2024-10-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_productoterminado_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.compra')),
                ('venta_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.ventasoftware')),
            ],
        ),
    ]
