# Generated by Django 4.2.9 on 2024-10-16 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_rename_clientes_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
